---
name: WWW-Google-Time
version: 0.0114
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: get time for various locations via Google
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Class::Data::Accessor: 0.04001
  LWP::UserAgent: 2.036
  URI: 1.35
configure_requires:
  Module::Build: 0.35
provides:
  WWW::Google::Time:
    file: lib/WWW/Google/Time.pm
    version: 0.0114
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
