---
name: WWW-Google-Time
version: 0.0103
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: get time for various locations via Google
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Data::Accessor: 0.04001
  LWP::UserAgent: 2.036
  URI: 1.35
build_requires:
  Test::More: 0
provides:
  WWW::Google::Time:
    file: lib/WWW/Google/Time.pm
    version: 0.0103
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
